/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './bhatest-anmodule.module';
import * as import2 from './services/bhatest-hola.service';
import * as import3 from '@angular/core/src/di/injector';
class BhatetsAnModuleInjector extends import0.NgModuleInjector<import1.BhatetsAnModule> {
  _BhatetsAnModule_0:import1.BhatetsAnModule;
  __BhatestHolaService_1:import2.BhatestHolaService;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BhatestHolaService_1():import2.BhatestHolaService {
    if ((this.__BhatestHolaService_1 == null)) { (this.__BhatestHolaService_1 = new import2.BhatestHolaService()); }
    return this.__BhatestHolaService_1;
  }
  createInternal():import1.BhatetsAnModule {
    this._BhatetsAnModule_0 = new import1.BhatetsAnModule();
    return this._BhatetsAnModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.BhatetsAnModule)) { return this._BhatetsAnModule_0; }
    if ((token === import2.BhatestHolaService)) { return this._BhatestHolaService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BhatetsAnModuleNgFactory:import0.NgModuleFactory<import1.BhatetsAnModule> = new import0.NgModuleFactory(BhatetsAnModuleInjector,import1.BhatetsAnModule);